name: Generate BuildCharts
description: Runs `buildcharts generate` using Docker
branding:
  icon: 'pie-chart'
  color: 'yellow'
runs:
  using: composite
  steps:
    - name: Generate BuildCharts
      uses: pyTooling/Actions/with-post-step@r0
      with:
        main: |
          echo "::group::buildcharts version"
          docker run --rm buildcharts/buildcharts:latest version
          echo "::endgroup::"

          echo "::group::buildcharts generate"
          docker run --rm -v "${GITHUB_WORKSPACE}:/src" -w /src -u "$(id -u):$(id -g)" buildcharts/buildcharts:latest generate
          echo "::endgroup::"

          echo "::group::Inspect build.yml"
          cat "${GITHUB_WORKSPACE}/build.yml"
          echo "::endgroup::"

          echo "::group::Inspect buildcharts.hcl"
          cat "${GITHUB_WORKSPACE}/buildcharts.hcl"
          echo "::endgroup::"
        post: |
          echo "Removing .buildcharts folder..."
          rm -rf "${GITHUB_WORKSPACE}/.buildcharts" || true

          echo "Removing buildcharts.hcl file..."
          rm -rf "${GITHUB_WORKSPACE}/buildcharts.hcl" || true


        